"use client";
import { useState, useEffect, useCallback } from "react";
import { useGoogleLogin } from "@react-oauth/google";
import { X, Zap, Check, AlertCircle, LogIn } from "lucide-react";
import { SITE } from "@/lib/config";

/* ══════════════════════════════════════════════════
   STORAGE — keeps Pro active across page loads
══════════════════════════════════════════════════ */
const STORE_KEY    = "pdfbb_pro_v3";
const VERIFY_EVERY = 7 * 24 * 60 * 60 * 1000; // re-verify every 7 days

interface ProData {
  token:        string;
  emailHash:    string;
  expires:      number;
  lastVerified: number;
  name:         string; // display name e.g. "Ali Khan"
}

function readPro(): ProData | null {
  try {
    const raw = localStorage.getItem(STORE_KEY);
    if (!raw) return null;
    const d = JSON.parse(raw) as ProData;
    if (!d.token || !d.emailHash || !d.expires) return null;
    return d;
  } catch { return null; }
}

function savePro(d: ProData): void {
  try {
    localStorage.setItem(STORE_KEY, JSON.stringify(d));
    // clean up old keys
    ["pdfbb_pro_v2", "pdfbb_pro_until"].forEach(k => {
      try { localStorage.removeItem(k); } catch {}
    });
  } catch {}
}

function clearPro(): void {
  try {
    ["pdfbb_pro_v3", "pdfbb_pro_v2", "pdfbb_pro_until"].forEach(k => {
      try { localStorage.removeItem(k); } catch {}
    });
  } catch {}
}

/* ══════════════════════════════════════════════════
   HOOK — useProStatus
══════════════════════════════════════════════════ */
export function useProStatus() {
  const [isPro,     setIsPro]     = useState(false);
  const [isLoaded,  setIsLoaded]  = useState(false);
  const [proName,   setProName]   = useState("");
  const [justPaid,  setJustPaid]  = useState(false);

  const refresh = useCallback(async () => {
    const d = readPro();

    if (!d || Date.now() > d.expires) {
      clearPro();
      setIsPro(false);
      setIsLoaded(true);
      return;
    }

    setIsPro(true);
    setProName(d.name || "");
    setIsLoaded(true);

    // Background re-verify every 7 days
    if (Date.now() - d.lastVerified > VERIFY_EVERY) {
      try {
        const res  = await fetch("/api/verify", {
          method:  "POST",
          headers: { "Content-Type": "application/json" },
          body:    JSON.stringify({ token: d.token }),
        });
        const json: { valid: boolean } = await res.json();
        if (!json.valid) {
          clearPro();
          setIsPro(false);
          setProName("");
        } else {
          savePro({ ...d, lastVerified: Date.now() });
        }
      } catch {
        // Network error — keep Pro (benefit of doubt)
      }
    }
  }, []);

  useEffect(() => {
    if (typeof window !== "undefined") {
      const params = new URLSearchParams(window.location.search);
      if (params.get("pro") === "success") {
        window.history.replaceState({}, "", window.location.pathname);
        setJustPaid(true);
      }
    }
    refresh();
  }, [refresh]);

  const activate = useCallback(
    (token: string, emailHash: string, expires: number, name: string) => {
      savePro({ token, emailHash, expires, name, lastVerified: Date.now() });
      setIsPro(true);
      setProName(name);
      setJustPaid(false);
    },
    []
  );

  const deactivate = useCallback(() => {
    clearPro();
    setIsPro(false);
    setProName("");
  }, []);

  return { isPro, isLoaded, proName, justPaid, activate, deactivate };
}

/* ══════════════════════════════════════════════════
   FEATURES LIST
══════════════════════════════════════════════════ */
const FEATURES = [
  'Remove "Generated by pdfbillbuilder.com" footer',
  "Zero ads — no ad modal on download or print",
  "12 premium accent colour themes",
  "White-label PDF — zero branding",
  "Works on all your devices (just sign in)",
];

/* ══════════════════════════════════════════════════
   TYPES
══════════════════════════════════════════════════ */
type View = "upgrade" | "login" | "loading" | "success" | "not-subscribed";

interface Props {
  open:       boolean;
  onClose:    () => void;
  onActivate: (token: string, emailHash: string, expires: number, name: string) => void;
  justPaid?:  boolean;
}

/* ══════════════════════════════════════════════════
   GOOGLE BUTTON — extracted so it can use the hook
══════════════════════════════════════════════════ */
function GoogleSignInBtn({
  label,
  onIdToken,
  disabled,
}: {
  label: string;
  onIdToken: (idToken: string) => void;
  disabled: boolean;
}) {
  const login = useGoogleLogin({
    flow:    "implicit",
    onSuccess: async (tokenRes) => {
      // exchange access token for ID token via userinfo
      try {
        const r = await fetch(
          "https://www.googleapis.com/oauth2/v3/userinfo",
          { headers: { Authorization: `Bearer ${tokenRes.access_token}` } }
        );
        const info = await r.json();
        // We send the access token to our server which will verify via tokeninfo
        // But we actually need the ID token — use the credential flow instead.
        // For now pass the sub + email in a custom way; the server will re-verify.
        // NOTE: useGoogleLogin implicit flow returns access_token, not id_token.
        // We work around this by sending the access_token and verifying via userinfo server-side.
        onIdToken(`access:${tokenRes.access_token}`);
      } catch {
        onIdToken(`access:${tokenRes.access_token}`);
      }
    },
    onError: () => {},
  });

  return (
    <button
      onClick={() => !disabled && login()}
      disabled={disabled}
      style={{
        display: "flex", alignItems: "center", justifyContent: "center", gap: 10,
        width: "100%", padding: "13px 20px", borderRadius: 12,
        border: "1.5px solid #e4e9f2", background: disabled ? "#f8fafc" : "white",
        cursor: disabled ? "not-allowed" : "pointer",
        fontSize: 14, fontWeight: 600, color: "#374151",
        boxShadow: "0 1px 4px rgba(0,0,0,0.06)",
        transition: "all .15s",
      }}
    >
      {/* Google logo SVG */}
      <svg width="18" height="18" viewBox="0 0 48 48" fill="none">
        <path fill="#EA4335" d="M24 9.5c3.54 0 6.71 1.22 9.21 3.6l6.85-6.85C35.9 2.38 30.47 0 24 0 14.62 0 6.51 5.38 2.56 13.22l7.98 6.19C12.43 13.72 17.74 9.5 24 9.5z"/>
        <path fill="#4285F4" d="M46.98 24.55c0-1.57-.15-3.09-.38-4.55H24v9.02h12.94c-.58 2.96-2.26 5.48-4.78 7.18l7.73 6c4.51-4.18 7.09-10.36 7.09-17.65z"/>
        <path fill="#FBBC05" d="M10.53 28.59c-.48-1.45-.76-2.99-.76-4.59s.27-3.14.76-4.59l-7.98-6.19C.92 16.46 0 20.12 0 24c0 3.88.92 7.54 2.56 10.78l7.97-6.19z"/>
        <path fill="#34A853" d="M24 48c6.48 0 11.93-2.13 15.89-5.81l-7.73-6c-2.15 1.45-4.92 2.3-8.16 2.3-6.26 0-11.57-4.22-13.47-9.91l-7.98 6.19C6.51 42.62 14.62 48 24 48z"/>
      </svg>
      {label}
    </button>
  );
}

/* ══════════════════════════════════════════════════
   MAIN COMPONENT
══════════════════════════════════════════════════ */
export default function ProModal({ open, onClose, onActivate, justPaid }: Props) {
  const [view,      setView]      = useState<View>("upgrade");
  const [error,     setError]     = useState("");
  const [userEmail, setUserEmail] = useState("");

  // Reset on open
  useEffect(() => {
    if (open) {
      setView(justPaid ? "login" : "upgrade");
      setError("");
      setUserEmail("");
    }
  }, [open, justPaid]);

  async function handleIdToken(idToken: string) {
    setView("loading");
    setError("");

    try {
      const res = await fetch("/api/auth/google", {
        method:  "POST",
        headers: { "Content-Type": "application/json" },
        body:    JSON.stringify({ idToken }),
      });

      const data: {
        valid: boolean;
        subscribed?: boolean;
        token?: string;
        emailHash?: string;
        expires?: number;
        name?: string;
        email?: string;
        error?: string;
      } = await res.json();

      if (data.valid && data.token && data.emailHash && data.expires) {
        onActivate(data.token, data.emailHash, data.expires, data.name ?? "");
        setView("success");
      } else if (data.subscribed === false) {
        setUserEmail(data.email ?? "");
        setView("not-subscribed");
      } else {
        setError(data.error ?? "Something went wrong. Please try again.");
        setView("login");
      }
    } catch {
      setError("Network error. Please check your connection.");
      setView("login");
    }
  }

  if (!open) return null;

  const busy = view === "loading";

  const heading =
    view === "success"         ? "Pro Activated! 🎉" :
    view === "loading"         ? "Verifying…"        :
    view === "not-subscribed"  ? "No Active Plan"    :
    justPaid                   ? "Payment Successful! 🎉" :
                                 `Unlock Pro · ${SITE.stripe.priceLabel}`;

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-4"
      style={{ background: "rgba(15,23,42,0.6)", backdropFilter: "blur(6px)" }}
      onClick={e => { if (e.target === e.currentTarget) onClose(); }}
    >
      <div
        className="relative w-full max-w-md rounded-3xl bg-white shadow-2xl overflow-hidden"
        onClick={e => e.stopPropagation()}
      >
        {/* ── Header ── */}
        <div style={{ background: "linear-gradient(135deg,#4f46e5,#7c3aed)", padding: "24px 28px 20px" }}>
          <button
            onClick={onClose}
            aria-label="Close"
            style={{ position: "absolute", top: 16, right: 16, background: "none", border: "none", cursor: "pointer", padding: 4 }}
          >
            <X size={20} color="rgba(255,255,255,0.7)" />
          </button>
          <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 8 }}>
            <Zap size={15} color="#fde68a" />
            <span style={{ fontSize: 11, fontWeight: 700, letterSpacing: "0.1em", textTransform: "uppercase" as const, color: "rgba(255,255,255,0.7)" }}>
              PDF Bill Builder Pro
            </span>
          </div>
          <p style={{ fontSize: 22, fontWeight: 900, color: "white", letterSpacing: "-0.03em", lineHeight: 1.25, margin: 0 }}>
            {heading}
          </p>
          {view === "upgrade" && (
            <p style={{ fontSize: 13, color: "rgba(255,255,255,0.7)", marginTop: 6 }}>
              Cancel anytime · All devices · No ads
            </p>
          )}
          {view === "login" && justPaid && (
            <p style={{ fontSize: 13, color: "rgba(255,255,255,0.8)", marginTop: 6 }}>
              Sign in with the Google account you used to pay.
            </p>
          )}
        </div>

        {/* ── Body ── */}
        <div style={{ padding: "22px 28px 26px" }}>

          {/* UPGRADE */}
          {view === "upgrade" && (
            <>
              <ul style={{ listStyle: "none", margin: "0 0 20px", padding: 0, display: "flex", flexDirection: "column", gap: 10 }}>
                {FEATURES.map(f => (
                  <li key={f} style={{ display: "flex", alignItems: "flex-start", gap: 10 }}>
                    <span style={{ width: 20, height: 20, borderRadius: "50%", background: "#ede9fe", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0, marginTop: 1 }}>
                      <Check size={11} color="#7c3aed" strokeWidth={3} />
                    </span>
                    <span style={{ fontSize: 13.5, color: "#374151", fontWeight: 500 }}>{f}</span>
                  </li>
                ))}
              </ul>

              <a
                href={`${SITE.stripe.proLink}?checkout[redirect_url]=${encodeURIComponent("https://www.pdfbillbuilder.com/?pro=success")}`}
                style={{
                  display: "flex", alignItems: "center", justifyContent: "center", gap: 8,
                  width: "100%", padding: "14px 20px", borderRadius: 14,
                  background: "linear-gradient(135deg,#4f46e5,#7c3aed)",
                  color: "white", fontSize: 15, fontWeight: 700,
                  textDecoration: "none", boxShadow: "0 4px 16px rgba(79,70,229,0.35)",
                }}
              >
                <Zap size={16} /> Get Pro — {SITE.stripe.priceLabel}
              </a>

              <div style={{ display: "flex", alignItems: "center", gap: 10, margin: "14px 0 10px" }}>
                <div style={{ flex: 1, height: 1, background: "#f0f3fa" }} />
                <span style={{ fontSize: 12, color: "#94a3b8", fontWeight: 500 }}>Already subscribed?</span>
                <div style={{ flex: 1, height: 1, background: "#f0f3fa" }} />
              </div>

              <GoogleSignInBtn
                label="Sign in with Google to activate"
                onIdToken={handleIdToken}
                disabled={busy}
              />
              <p style={{ textAlign: "center" as const, fontSize: 11.5, color: "#94a3b8", marginTop: 10 }}>
                Secure checkout via Lemon Squeezy.
              </p>
            </>
          )}

          {/* LOGIN */}
          {(view === "login" || view === "loading") && (
            <>
              {justPaid && (
                <div style={{ padding: "11px 14px", borderRadius: 10, background: "#f0fdf4", border: "1.5px solid #bbf7d0", marginBottom: 16 }}>
                  <p style={{ fontSize: 13, color: "#15803d", fontWeight: 600, margin: 0 }}>
                    ✅ Payment confirmed! Now sign in with Google to activate Pro.
                  </p>
                </div>
              )}
              {error && (
                <div style={{ display: "flex", gap: 8, padding: "10px 14px", borderRadius: 10, background: "#fef2f2", border: "1.5px solid #fecaca", marginBottom: 14 }}>
                  <AlertCircle size={15} color="#ef4444" style={{ flexShrink: 0, marginTop: 1 }} />
                  <p style={{ fontSize: 13, color: "#ef4444", margin: 0 }}>{error}</p>
                </div>
              )}
              <p style={{ fontSize: 13.5, color: "#475569", lineHeight: 1.65, marginBottom: 18 }}>
                Sign in with the Google account you used when purchasing Pro.
                Your email is your unique ID — no passwords needed.
              </p>
              <GoogleSignInBtn
                label={busy ? "Verifying…" : "Continue with Google"}
                onIdToken={handleIdToken}
                disabled={busy}
              />
              {busy && (
                <div style={{ display: "flex", alignItems: "center", justifyContent: "center", gap: 8, marginTop: 14, color: "#94a3b8", fontSize: 13 }}>
                  <svg style={{ animation: "spin .8s linear infinite", width: 16, height: 16 }} fill="none" viewBox="0 0 24 24">
                    <circle style={{ opacity: .25 }} cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/>
                    <path style={{ opacity: .8 }} fill="currentColor" d="M4 12a8 8 0 018-8v8H4z"/>
                  </svg>
                  Checking subscription…
                </div>
              )}
              {!justPaid && !busy && (
                <button
                  onClick={() => { setView("upgrade"); setError(""); }}
                  style={{ display: "block", width: "100%", marginTop: 12, padding: 10, background: "none", border: "none", color: "#94a3b8", fontSize: 13, cursor: "pointer", textAlign: "center" as const }}
                >
                  ← Back
                </button>
              )}
            </>
          )}

          {/* NOT SUBSCRIBED */}
          {view === "not-subscribed" && (
            <>
              <div style={{ padding: "12px 14px", borderRadius: 10, background: "#fff7ed", border: "1.5px solid #fed7aa", marginBottom: 16 }}>
                <p style={{ fontSize: 13, color: "#c2410c", fontWeight: 600, margin: 0 }}>
                  No active Pro subscription found{userEmail ? ` for ${userEmail}` : ""}.
                </p>
              </div>
              <p style={{ fontSize: 13.5, color: "#475569", lineHeight: 1.65, marginBottom: 18 }}>
                Make sure you sign in with the same Google account you used to purchase.
                If you just paid, please wait 1–2 minutes and try again.
              </p>
              <a
                href={`${SITE.stripe.proLink}?checkout[redirect_url]=${encodeURIComponent("https://www.pdfbillbuilder.com/?pro=success")}`}
                style={{
                  display: "flex", alignItems: "center", justifyContent: "center", gap: 8,
                  width: "100%", padding: "13px 20px", borderRadius: 12,
                  background: "linear-gradient(135deg,#4f46e5,#7c3aed)",
                  color: "white", fontSize: 14, fontWeight: 700,
                  textDecoration: "none", boxShadow: "0 4px 16px rgba(79,70,229,0.3)",
                }}
              >
                <Zap size={15} /> Subscribe Now — {SITE.stripe.priceLabel}
              </a>
              <button
                onClick={() => { setView("login"); setError(""); }}
                style={{ display: "block", width: "100%", marginTop: 10, padding: 10, background: "none", border: "none", color: "#94a3b8", fontSize: 13, cursor: "pointer", textAlign: "center" as const }}
              >
                Try a different account
              </button>
            </>
          )}

          {/* SUCCESS */}
          {view === "success" && (
            <div style={{ textAlign: "center" as const, padding: "4px 0 2px" }}>
              <div style={{ fontSize: 52, marginBottom: 14 }}>🎉</div>
              <p style={{ fontSize: 16, fontWeight: 800, color: "#0d1117", marginBottom: 8, letterSpacing: "-0.02em" }}>
                Pro is now active!
              </p>
              <p style={{ fontSize: 13.5, color: "#64748b", lineHeight: 1.7, marginBottom: 22 }}>
                Watermark removed. Ads disabled. 12 premium colours unlocked.<br />
                Sign in with Google any time to restore Pro on a new device.
              </p>
              <button
                onClick={onClose}
                style={{
                  padding: "12px 36px", borderRadius: 12, border: "none",
                  background: "linear-gradient(135deg,#4f46e5,#7c3aed)",
                  color: "white", fontSize: 14, fontWeight: 700, cursor: "pointer",
                  boxShadow: "0 4px 16px rgba(79,70,229,0.3)",
                }}
              >
                Start Using Pro ✓
              </button>
            </div>
          )}

        </div>
        <style>{`@keyframes spin{to{transform:rotate(360deg)}}`}</style>
      </div>
    </div>
  );
}
