"use client";
import { useState, useEffect } from "react";
import { X, Zap, Check } from "lucide-react";
import { SITE } from "@/lib/config";

const PRO_KEY = "pdfbb_pro_until";

export function useProStatus() {
  const [isPro, setIsPro] = useState(false);

  useEffect(() => {
    try {
      const until = localStorage.getItem(PRO_KEY);
      if (until && Date.now() < parseInt(until)) setIsPro(true);
    } catch {}

    // Check URL param after Stripe redirect
    const params = new URLSearchParams(window.location.search);
    if (params.get("pro") === "success") {
      // Grant 35 days (a bit over 1 month for safety)
      const until = Date.now() + 35 * 24 * 60 * 60 * 1000;
      try { localStorage.setItem(PRO_KEY, String(until)); } catch {}
      setIsPro(true);
      // Clean URL
      window.history.replaceState({}, "", window.location.pathname);
    }
  }, []);

  return isPro;
}

const FEATURES = [
  "Remove 'Generated by pdfbillbuilder.com' footer",
  "12 premium accent colour themes",
  "White-label — no branding on your PDFs",
  "Priority email support",
  "All future Pro features included",
];

export default function ProModal({ open, onClose }: { open: boolean; onClose: () => void }) {
  if (!open) return null;

  const proLink = SITE.stripe.proLink;

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-4"
      style={{ background: "rgba(15,23,42,0.55)", backdropFilter: "blur(4px)" }}
      onClick={e => { if (e.target === e.currentTarget) onClose(); }}
    >
      <div className="relative w-full max-w-md rounded-3xl bg-white shadow-2xl overflow-hidden">

        {/* Header gradient */}
        <div style={{ background: "linear-gradient(135deg,#4f46e5,#7c3aed)", padding: "28px 28px 20px" }}>
          <button onClick={onClose} className="absolute top-4 right-4 text-white/70 hover:text-white transition-colors">
            <X size={20} />
          </button>
          <div className="flex items-center gap-3 mb-3">
            <div style={{ background: "rgba(255,255,255,0.2)", borderRadius: 10, padding: "6px 8px", display: "inline-flex" }}>
              <Zap size={18} className="text-yellow-300" />
            </div>
            <span style={{ fontSize: 12, fontWeight: 700, letterSpacing: "0.1em", textTransform: "uppercase", color: "rgba(255,255,255,0.8)" }}>
              PDF Bill Builder Pro
            </span>
          </div>
          <p style={{ fontSize: 28, fontWeight: 900, color: "white", letterSpacing: "-0.03em", lineHeight: 1.2 }}>
            Go Pro for<br />
            <span style={{ color: "#fde68a" }}>{SITE.stripe.priceLabel}</span>
          </p>
          <p style={{ fontSize: 13.5, color: "rgba(255,255,255,0.75)", marginTop: 8 }}>
            Cancel any time. Instant access.
          </p>
        </div>

        {/* Features */}
        <div style={{ padding: "20px 28px" }}>
          <ul style={{ listStyle: "none", margin: 0, padding: 0, display: "flex", flexDirection: "column", gap: 11 }}>
            {FEATURES.map((f) => (
              <li key={f} style={{ display: "flex", alignItems: "flex-start", gap: 10 }}>
                <span style={{ width: 20, height: 20, borderRadius: "50%", background: "#ede9fe", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0, marginTop: 1 }}>
                  <Check size={11} color="#7c3aed" strokeWidth={3} />
                </span>
                <span style={{ fontSize: 13.5, color: "#374151", fontWeight: 500 }}>{f}</span>
              </li>
            ))}
          </ul>

          {/* CTA */}
          <div style={{ marginTop: 22 }}>
            {proLink ? (
              <a
                href={`${proLink}?checkout[redirect_url]=${encodeURIComponent("https://www.pdfbillbuilder.com/?pro=success")}`}
                style={{
                  display: "flex", alignItems: "center", justifyContent: "center", gap: 8,
                  width: "100%", padding: "14px 20px", borderRadius: 14, border: "none",
                  background: "linear-gradient(135deg,#4f46e5,#7c3aed)",
                  color: "white", fontSize: 15, fontWeight: 700, cursor: "pointer",
                  textDecoration: "none", boxShadow: "0 4px 16px rgba(79,70,229,0.4)",
                }}
              >
                <Zap size={16} />
                Upgrade to Pro — {SITE.stripe.priceLabel}
              </a>
            ) : (
              <div style={{ textAlign: "center", padding: "14px", borderRadius: 14, background: "#f8fafc", border: "1px solid #e4e9f2" }}>
                <p style={{ fontSize: 13, color: "#94a3b8", fontWeight: 500 }}>
                  Pro coming soon — add Stripe link in config to activate
                </p>
              </div>
            )}
          </div>

          <p style={{ textAlign: "center", fontSize: 11.5, color: "#94a3b8", marginTop: 12 }}>
            Secure payment via Stripe. Cancel any time from your Stripe dashboard.
          </p>
        </div>
      </div>
    </div>
  );
}
