"use client";
import { useState, useEffect, useCallback } from "react";
import { X, Zap, Check, Key, AlertCircle } from "lucide-react";
import { SITE } from "@/lib/config";

/* ══════════════════════════════════════════════════
   STORAGE
══════════════════════════════════════════════════ */
const STORE_KEY    = "pdfbb_pro_v2";
const VERIFY_EVERY = 7 * 24 * 60 * 60 * 1000; // 7 days

interface ProData {
  token:        string;
  keyHash:      string;
  expires:      number;
  lastVerified: number;
}

function readPro(): ProData | null {
  try {
    const raw = localStorage.getItem(STORE_KEY);
    if (!raw) return null;
    const d = JSON.parse(raw) as ProData;
    if (!d.token || !d.keyHash || !d.expires || !d.lastVerified) return null;
    return d;
  } catch { return null; }
}

function savePro(d: ProData): void {
  try { localStorage.setItem(STORE_KEY, JSON.stringify(d)); } catch {}
}

function clearPro(): void {
  try {
    localStorage.removeItem(STORE_KEY);
    localStorage.removeItem("pdfbb_pro_until"); // remove legacy v1
  } catch {}
}

/* ══════════════════════════════════════════════════
   HOOK — useProStatus
══════════════════════════════════════════════════ */
export function useProStatus() {
  const [isPro,         setIsPro]         = useState(false);
  const [isLoaded,      setIsLoaded]      = useState(false);
  const [justPaid,      setJustPaid]      = useState(false);

  /** Re-check stored token (called on mount + after activation) */
  const refresh = useCallback(async () => {
    const d = readPro();

    // No data or expired → not pro
    if (!d || Date.now() > d.expires) {
      clearPro();
      setIsPro(false);
      setIsLoaded(true);
      return;
    }

    // Expiry OK → mark as pro immediately (fast, no network)
    setIsPro(true);
    setIsLoaded(true);

    // Background re-verify with server every 7 days
    if (Date.now() - d.lastVerified > VERIFY_EVERY) {
      try {
        const res  = await fetch("/api/verify", {
          method:  "POST",
          headers: { "Content-Type": "application/json" },
          body:    JSON.stringify({ token: d.token }),
        });
        const json: { valid: boolean } = await res.json();

        if (!json.valid) {
          clearPro();
          setIsPro(false);
        } else {
          savePro({ ...d, lastVerified: Date.now() });
        }
      } catch {
        // Network error — keep pro (benefit of doubt)
      }
    }
  }, []);

  useEffect(() => {
    // Handle ?pro=success redirect from Lemon Squeezy
    if (typeof window !== "undefined") {
      const params = new URLSearchParams(window.location.search);
      if (params.get("pro") === "success") {
        window.history.replaceState({}, "", window.location.pathname);
        setJustPaid(true);
      }
    }
    refresh();
  }, [refresh]);

  /** Call this after successful key activation */
  const activate = useCallback((token: string, keyHash: string, expires: number) => {
    savePro({ token, keyHash, expires, lastVerified: Date.now() });
    setIsPro(true);
    setJustPaid(false);
  }, []);

  return { isPro, isLoaded, justPaid, activate };
}

/* ══════════════════════════════════════════════════
   FEATURES LIST
══════════════════════════════════════════════════ */
const FEATURES = [
  'Remove "Generated by pdfbillbuilder.com" footer',
  "12 premium accent colour themes",
  "White-label — zero branding on your PDFs",
  "Use on up to 5 devices with one key",
  "All future Pro features included",
];

/* ══════════════════════════════════════════════════
   TYPES
══════════════════════════════════════════════════ */
type View = "upgrade" | "activate" | "loading" | "success";

interface Props {
  open:            boolean;
  onClose:         () => void;
  onActivate:      (token: string, keyHash: string, expires: number) => void;
  justPaid?:       boolean;
}

/* ══════════════════════════════════════════════════
   COMPONENT
══════════════════════════════════════════════════ */
export default function ProModal({ open, onClose, onActivate, justPaid }: Props) {
  const [view,  setView]  = useState<View>("upgrade");
  const [key,   setKey]   = useState("");
  const [error, setError] = useState("");

  // Reset state on open
  useEffect(() => {
    if (open) {
      setView(justPaid ? "activate" : "upgrade");
      setKey("");
      setError("");
    }
  }, [open, justPaid]);

  async function handleActivate() {
    const trimmed = key.trim();

    // Client-side format check (UUID pattern)
    if (!trimmed) {
      setError("Please enter your license key.");
      return;
    }
    const uuidRe = /^[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}$/i;
    if (!uuidRe.test(trimmed)) {
      setError("Invalid format. Your key looks like: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX");
      return;
    }

    setView("loading");
    setError("");

    try {
      const res = await fetch("/api/activate", {
        method:  "POST",
        headers: { "Content-Type": "application/json" },
        body:    JSON.stringify({ key: trimmed }),
      });
      const data: { valid: boolean; token?: string; keyHash?: string; expires?: number; error?: string } = await res.json();

      if (data.valid && data.token && data.keyHash && data.expires) {
        onActivate(data.token, data.keyHash, data.expires);
        setView("success");
      } else {
        setError(data.error ?? "Activation failed. Please try again.");
        setView("activate");
      }
    } catch {
      setError("Network error. Please check your connection and try again.");
      setView("activate");
    }
  }

  if (!open) return null;

  const busy = view === "loading";

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-4"
      style={{ background: "rgba(15,23,42,0.6)", backdropFilter: "blur(6px)" }}
      onClick={e => { if (e.target === e.currentTarget) onClose(); }}
    >
      <div
        className="relative w-full max-w-md rounded-3xl bg-white shadow-2xl overflow-hidden"
        onClick={e => e.stopPropagation()}
      >
        {/* ── Header ── */}
        <div style={{ background: "linear-gradient(135deg,#4f46e5,#7c3aed)", padding: "24px 28px 20px" }}>
          <button
            onClick={onClose}
            aria-label="Close"
            style={{ position: "absolute", top: 16, right: 16, background: "none", border: "none", cursor: "pointer", color: "rgba(255,255,255,0.7)", lineHeight: 1 }}
          >
            <X size={20} />
          </button>

          <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 8 }}>
            <Zap size={15} color="#fde68a" />
            <span style={{ fontSize: 11, fontWeight: 700, letterSpacing: "0.1em", textTransform: "uppercase" as const, color: "rgba(255,255,255,0.7)" }}>
              PDF Bill Builder Pro
            </span>
          </div>

          <p style={{ fontSize: 22, fontWeight: 900, color: "white", letterSpacing: "-0.03em", lineHeight: 1.25, margin: 0 }}>
            {view === "success"  ? "Pro Activated! 🎉"
            : view === "loading" ? "Verifying…"
            : justPaid           ? "Payment Successful! 🎉"
            :                      `Unlock Pro · ${SITE.stripe.priceLabel}`}
          </p>

          {view === "upgrade" && (
            <p style={{ fontSize: 13, color: "rgba(255,255,255,0.7)", marginTop: 6 }}>
              Cancel anytime · Instant access · 5 devices
            </p>
          )}
          {(view === "activate" || view === "loading") && justPaid && (
            <p style={{ fontSize: 13, color: "rgba(255,255,255,0.8)", marginTop: 6 }}>
              Check your email for the license key and paste it below.
            </p>
          )}
        </div>

        {/* ── Body ── */}
        <div style={{ padding: "22px 28px 26px" }}>

          {/* UPGRADE VIEW */}
          {view === "upgrade" && (
            <>
              <ul style={{ listStyle: "none", margin: "0 0 20px", padding: 0, display: "flex", flexDirection: "column", gap: 11 }}>
                {FEATURES.map(f => (
                  <li key={f} style={{ display: "flex", alignItems: "flex-start", gap: 10 }}>
                    <span style={{ width: 20, height: 20, borderRadius: "50%", background: "#ede9fe", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0, marginTop: 1 }}>
                      <Check size={11} color="#7c3aed" strokeWidth={3} />
                    </span>
                    <span style={{ fontSize: 13.5, color: "#374151", fontWeight: 500 }}>{f}</span>
                  </li>
                ))}
              </ul>

              <a
                href={`${SITE.stripe.proLink}?checkout[redirect_url]=${encodeURIComponent("https://www.pdfbillbuilder.com/?pro=success")}`}
                style={{
                  display: "flex", alignItems: "center", justifyContent: "center", gap: 8,
                  width: "100%", padding: "14px 20px", borderRadius: 14,
                  background: "linear-gradient(135deg,#4f46e5,#7c3aed)",
                  color: "white", fontSize: 15, fontWeight: 700,
                  textDecoration: "none", boxShadow: "0 4px 16px rgba(79,70,229,0.35)",
                }}
              >
                <Zap size={16} /> Upgrade to Pro — {SITE.stripe.priceLabel}
              </a>

              <button
                onClick={() => { setView("activate"); setError(""); }}
                style={{
                  display: "flex", alignItems: "center", justifyContent: "center", gap: 6,
                  width: "100%", marginTop: 10, padding: "10px 16px", borderRadius: 12,
                  border: "1.5px solid #e4e9f2", background: "white",
                  color: "#64748b", fontSize: 13, fontWeight: 600, cursor: "pointer",
                }}
              >
                <Key size={13} /> I already have a license key
              </button>

              <p style={{ textAlign: "center", fontSize: 11.5, color: "#94a3b8", marginTop: 12 }}>
                Secure checkout via Lemon Squeezy. Cancel anytime.
              </p>
            </>
          )}

          {/* ACTIVATE VIEW */}
          {(view === "activate" || view === "loading") && (
            <>
              {/* Payment success banner */}
              {justPaid && (
                <div style={{ padding: "11px 14px", borderRadius: 10, background: "#f0fdf4", border: "1.5px solid #bbf7d0", marginBottom: 16 }}>
                  <p style={{ fontSize: 13, color: "#15803d", fontWeight: 600, margin: 0 }}>
                    ✅ Payment confirmed! Lemon Squeezy has sent your license key to your email.
                  </p>
                </div>
              )}

              <label style={{ display: "block", fontSize: 11.5, fontWeight: 700, letterSpacing: "0.07em", textTransform: "uppercase" as const, color: "#64748b", marginBottom: 8 }}>
                License Key
              </label>
              <input
                type="text"
                value={key}
                onChange={e => { setKey(e.target.value); setError(""); }}
                onKeyDown={e => e.key === "Enter" && !busy && handleActivate()}
                placeholder="XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
                disabled={busy}
                autoFocus
                style={{
                  width: "100%", padding: "11px 14px", fontSize: 13,
                  fontFamily: "monospace", letterSpacing: "0.05em",
                  border: `1.5px solid ${error ? "#fca5a5" : "#e4e9f2"}`,
                  borderRadius: 10, background: busy ? "#f8fafc" : "white",
                  color: "#0d1117", outline: "none", boxSizing: "border-box" as const,
                  transition: "border-color .15s",
                }}
              />

              {/* Error message */}
              {error && (
                <div style={{ display: "flex", alignItems: "flex-start", gap: 6, marginTop: 8 }}>
                  <AlertCircle size={14} color="#ef4444" style={{ flexShrink: 0, marginTop: 1 }} />
                  <p style={{ fontSize: 12.5, color: "#ef4444", margin: 0, lineHeight: 1.5 }}>{error}</p>
                </div>
              )}

              <p style={{ fontSize: 12, color: "#94a3b8", margin: "8px 0 18px", lineHeight: 1.5 }}>
                Your license key was emailed to you by Lemon Squeezy right after purchase.
              </p>

              <button
                onClick={handleActivate}
                disabled={busy}
                style={{
                  display: "flex", alignItems: "center", justifyContent: "center", gap: 8,
                  width: "100%", padding: "13px 20px", borderRadius: 12, border: "none",
                  background: busy ? "#94a3b8" : "linear-gradient(135deg,#4f46e5,#7c3aed)",
                  color: "white", fontSize: 14, fontWeight: 700,
                  cursor: busy ? "not-allowed" : "pointer",
                  boxShadow: busy ? "none" : "0 4px 16px rgba(79,70,229,0.35)",
                  transition: "all .2s",
                }}
              >
                {busy ? (
                  <>
                    <svg style={{ animation: "spin .8s linear infinite", width: 16, height: 16 }} fill="none" viewBox="0 0 24 24">
                      <circle style={{ opacity: .25 }} cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/>
                      <path style={{ opacity: .8 }} fill="currentColor" d="M4 12a8 8 0 018-8v8H4z"/>
                    </svg>
                    Verifying…
                  </>
                ) : (
                  <><Key size={15} /> Activate Pro</>
                )}
              </button>

              {!justPaid && (
                <button
                  onClick={() => { setView("upgrade"); setError(""); setKey(""); }}
                  style={{
                    display: "block", width: "100%", marginTop: 10, padding: "10px",
                    background: "none", border: "none", color: "#94a3b8",
                    fontSize: 13, cursor: "pointer", textAlign: "center" as const,
                  }}
                >
                  ← Back
                </button>
              )}
            </>
          )}

          {/* SUCCESS VIEW */}
          {view === "success" && (
            <div style={{ textAlign: "center" as const, padding: "4px 0 2px" }}>
              <div style={{ fontSize: 52, marginBottom: 14 }}>🎉</div>
              <p style={{ fontSize: 16, fontWeight: 800, color: "#0d1117", marginBottom: 8, letterSpacing: "-0.02em" }}>
                Pro is now active!
              </p>
              <p style={{ fontSize: 13.5, color: "#64748b", lineHeight: 1.7, marginBottom: 22 }}>
                Watermark removed. 12 premium colour themes unlocked.<br />
                Enjoy white-label, professional PDFs!
              </p>
              <button
                onClick={onClose}
                style={{
                  padding: "12px 36px", borderRadius: 12, border: "none",
                  background: "linear-gradient(135deg,#4f46e5,#7c3aed)",
                  color: "white", fontSize: 14, fontWeight: 700, cursor: "pointer",
                  boxShadow: "0 4px 16px rgba(79,70,229,0.3)",
                }}
              >
                Start Using Pro ✓
              </button>
            </div>
          )}

        </div>
        <style>{`@keyframes spin{to{transform:rotate(360deg)}}`}</style>
      </div>
    </div>
  );
}
