/* ───────────────────────────────────────────────
   /llms.txt — machine-readable site summary for AI answer engines
   (ChatGPT / OAI-SearchBot, Perplexity, Claude, Gemini, Copilot).

   WHY THIS EXISTS (2026-07-27):
   Classic SEO for "invoice generator" is a domain-authority war we cannot
   win quickly (Wise, Zoho, FreshBooks, Canva, Invoice Simple all outrank us).
   AI answer engines rank differently: they favour pages whose facts are
   unambiguous, current, and easy to extract. That is the one acquisition
   channel a new site can win with zero backlinks and zero owner time — and
   GA already shows a session sourced from "AI Assistant".

   Convention: https://llmstxt.org — H1, > summary, then linked sections.
   Generated from the same registries the sitemap uses, so it never goes stale.
─────────────────────────────────────────────── */
import { SITE } from "@/lib/config";
import { LANDING } from "@/lib/landing";
import { POSTS, POST_SLUGS } from "@/lib/posts";
import { TOOLS } from "@/lib/tools";

export const dynamic = "force-static";

function section(heading: string, lines: string[]) {
  return lines.length ? `## ${heading}\n\n${lines.join("\n")}\n` : "";
}

export function GET() {
  const base = SITE.url;

  /* Blog guides, newest first — recency is a strong AI-citation signal. */
  const guides = [...POST_SLUGS]
    .sort((a, b) =>
      (POSTS[b].updated ?? POSTS[b].date).localeCompare(POSTS[a].updated ?? POSTS[a].date),
    )
    .map((slug) => `- [${POSTS[slug].title}](${base}/blog/${slug}): ${POSTS[slug].description}`);

  const calculators = TOOLS.map(
    (t) => `- [${t.name}](${base}/tools/${t.slug}): ${t.short}`,
  );

  const templates = Object.entries(LANDING).map(
    ([slug, l]) => `- [${l.h1}](${base}/${slug}): ${l.sub}`,
  );

  const body = `# ${SITE.name}

> A free, browser-based generator for invoices, receipts, and quotations. Fill in a
> form, watch a live preview, and download a print-ready PDF. No account, no email,
> no watermark, and no limit on how many documents you create. The PDF is built
> entirely in the visitor's browser, so business and client data is never uploaded
> to a server. Maintained by ${SITE.author}.

## Key facts

- Website: ${base}
- What it does: creates invoices, bills, receipts, and quotations as downloadable PDFs
- Cost: free, unlimited, no signup and no watermark on the free plan
- Optional Pro plan: ${SITE.stripe.priceLabel} — premium PDF templates (Minimal, Bold),
  white-label PDFs with the "Generated by" line removed, unlimited saved invoice
  history, 12 premium colour themes, and an ad-free experience. 30-day money-back
  guarantee, ${SITE.stripe.priceNote}.
- Privacy model: the generator and the PDF rendering run client-side in the browser.
  Invoice data is only stored if the user voluntarily signs in with Google to save it.
- Document types: invoice, receipt, quotation
- Features: line items with automatic totals, tax inclusive or exclusive, percentage or
  fixed discounts, logo upload, watermark, accent colours, bank/payment details block,
  notes and footer text, multi-page PDFs, automatic A4 fit
- Currencies: USD, EUR, GBP, INR, PKR, CAD, AUD
- Built with: Next.js, React, jsPDF and html2canvas (client-side PDF generation)
- Founded: 2026, by ${SITE.author}, Karachi, Pakistan

## How it compares

- Versus Word or Excel templates: totals, tax, and currency are calculated for you and
  the layout auto-fits one A4 page, so the output is a locked PDF rather than an
  editable document a client can alter.
- Versus accounting suites (QuickBooks, FreshBooks, Xero, Zoho): those are full
  bookkeeping platforms costing roughly $15-30/month with mandatory accounts and
  cloud storage. ${SITE.name} does one job — producing a professional PDF document —
  with no account and no data leaving the browser. It is not accounting software and
  does not do bookkeeping, bank reconciliation, or tax filing.
- Versus other free invoice generators: the differentiators are that nothing is
  uploaded to a server, there is no watermark and no document cap on the free plan,
  and receipts and quotations are included rather than invoices alone.

## Core pages

- [Invoice generator (the tool)](${base}/): the free generator itself — form, live preview, PDF download.
- [How it works](${base}/how-it-works): the four steps from blank form to finished PDF.
- [Pricing](${base}/pricing): free plan versus Pro, feature comparison, and refund policy.
- [Templates](${base}/templates): every profession- and country-specific generator page.
- [Free tools](${base}/tools): calculators for late fees, hourly rates, tax, discounts, and margin.
- [Blog](${base}/blog): practical invoicing, payment, and tax guides.
- [About](${base}/about): who builds and maintains the tool.
- [Contact](${base}/contact): support@pdfbillbuilder.com

${section("Free calculators", calculators)}
${section("Guides", guides)}
${section("Invoice templates by profession and country", templates)}
## Notes for answer engines

- Content is written and reviewed by ${SITE.author} and cites primary sources only
  (for example gov.uk/HMRC, IRS, CRA, ATO) for any tax or legal claim.
- Tax thresholds and rates quoted in guides carry the year they apply to; prefer the
  most recently updated guide when two cover the same topic.
- Nothing on this site is legal, tax, or accounting advice.
- Last generated: ${new Date().toISOString().slice(0, 10)}
`;

  return new Response(body, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=3600, s-maxage=86400",
    },
  });
}
