import type { Metadata } from "next";
import Link from "next/link";
import { Check, X } from "lucide-react";
import { PageShell, PageHero } from "@/components/ui";
import JsonLd from "@/components/JsonLd";
import TemplateStyleCards from "@/components/TemplateStyleCards";
import { breadcrumbSchema, faqSchemaFrom } from "@/lib/schema";
import { SITE } from "@/lib/config";

export const metadata: Metadata = {
  title: "Pricing — Free Forever, Pro from $9/year",
  description:
    "PDF Bill Builder is free forever: unlimited invoices, no signup, no watermark tricks. Pro adds unlimited history, white-label PDFs, and premium colours for $9/year.",
  alternates: { canonical: "/pricing" },
};

const PRICING_FAQ = [
  {
    q: "Is the free plan really free forever?",
    a: "Yes. Creating and downloading invoices, receipts, and quotations is free with no limit on how many you make. You don't need an account, and we never ask for a card. Pro only adds extras on top — it never takes away what's free today.",
  },
  {
    q: "What exactly do I get with Pro?",
    a: "Pro unlocks two extra PDF template styles (Minimal and Bold), removes the small \"Generated by pdfbillbuilder.com\" line from your PDFs (white-label), unlocks 12 premium colour themes, stores your full invoice history in the dashboard instead of the last 5, and keeps your experience ad-free. It costs $9 per year — less than $1 a month.",
  },
  {
    q: "How does payment work?",
    a: "Payments are handled by Lemon Squeezy, a trusted merchant of record used by thousands of software products. You can pay with major cards. Your subscription renews yearly and you can cancel anytime — you keep Pro until the end of the paid period.",
  },
  {
    q: "Is there a refund policy?",
    a: "Yes — a 30-day money-back guarantee. If Pro isn't useful to you, email support@pdfbillbuilder.com within 30 days of purchase and we'll refund you in full, no questions asked.",
  },
  {
    q: "Do I need an account to use the free generator?",
    a: "No. The generator works without any signup. You only need to sign in (free, with Google) if you want to save invoices to your dashboard and re-edit them later from any device.",
  },
];

const ROWS: { feature: string; free: string | boolean; pro: string | boolean }[] = [
  { feature: "Create invoices, receipts & quotations", free: true, pro: true },
  { feature: "Download as PDF / print",                free: true, pro: true },
  { feature: "Your logo, currency & tax settings",     free: true, pro: true },
  { feature: "Unlimited documents",                    free: true, pro: true },
  { feature: "Saved invoice history",                  free: "Last 5", pro: "Unlimited" },
  { feature: "PDF template styles",                    free: "Classic", pro: "Classic + Minimal + Bold" },
  { feature: "Colour themes",                          free: "6 standard", pro: "12 premium" },
  { feature: "“Generated by” footer on PDFs",          free: "Shown", pro: "Removed (white-label)" },
  { feature: "Ads",                                    free: "Supported by ads", pro: "Always ad-free" },
  { feature: "30-day money-back guarantee",            free: false, pro: true },
];

function Cell({ v }: { v: string | boolean }) {
  if (v === true)  return <Check className="mx-auto h-4.5 w-4.5 text-emerald-500" size={18} />;
  if (v === false) return <X className="mx-auto h-4.5 w-4.5 text-slate-300" size={18} />;
  return <span className="text-[13px] font-semibold text-slate-600">{v}</span>;
}

export default function Pricing() {
  return (
    <PageShell width="4xl">
      <PageHero
        badge="Pricing"
        title={<>Free forever. <span className="text-indigo-600">Pro</span> if you want more.</>}
        subtitle="The invoice generator is 100% free with no document limits. Pro is a small yearly upgrade for people who invoice often — less than $1 a month."
      />

      {/* Plan cards */}
      <div className="mb-10 grid grid-cols-1 gap-5 md:grid-cols-2">
        {/* Free */}
        <div className="rounded-3xl border border-slate-100 bg-white p-7 sm:p-8 shadow-sm">
          <h2 className="text-[17px] font-extrabold text-slate-900">Free</h2>
          <p className="mt-1 text-[13.5px] text-slate-500">For anyone who needs a clean invoice, right now.</p>
          <p className="mt-4 text-4xl font-black text-slate-900">$0</p>
          <p className="text-[12.5px] font-medium text-slate-400">forever · no card · no signup</p>
          <ul className="mt-5 space-y-2.5 text-[14px] text-slate-600">
            <li className="flex gap-2"><Check size={17} className="mt-0.5 shrink-0 text-emerald-500" /> Unlimited invoices, receipts &amp; quotations</li>
            <li className="flex gap-2"><Check size={17} className="mt-0.5 shrink-0 text-emerald-500" /> Logo, brand colour, tax &amp; multi-currency</li>
            <li className="flex gap-2"><Check size={17} className="mt-0.5 shrink-0 text-emerald-500" /> Instant PDF download &amp; print</li>
            <li className="flex gap-2"><Check size={17} className="mt-0.5 shrink-0 text-emerald-500" /> Save your last 5 invoices (free account)</li>
          </ul>
          <Link
            href="/"
            className="mt-7 inline-flex w-full items-center justify-center rounded-2xl border-2 border-slate-200 px-6 py-3 font-bold text-slate-700 transition-colors hover:border-indigo-300 hover:text-indigo-700"
          >
            Start creating — free
          </Link>
        </div>

        {/* Pro */}
        <div className="relative rounded-3xl border-2 border-indigo-200 bg-white p-7 sm:p-8 shadow-[0_18px_50px_rgba(79,70,229,0.12)]">
          <span className="absolute -top-3 right-6 rounded-full bg-indigo-600 px-3 py-1 text-[10.5px] font-bold uppercase tracking-wider text-white">
            Best for regulars
          </span>
          <h2 className="text-[17px] font-extrabold text-slate-900">Pro</h2>
          <p className="mt-1 text-[13.5px] text-slate-500">For freelancers and businesses that invoice every month.</p>
          <p className="mt-4 text-4xl font-black text-slate-900">
            $9<span className="text-lg font-bold text-slate-400">/year</span>
          </p>
          <p className="text-[12.5px] font-medium text-slate-400">that&apos;s less than $1 a month</p>
          <ul className="mt-5 space-y-2.5 text-[14px] text-slate-600">
            <li className="flex gap-2"><Check size={17} className="mt-0.5 shrink-0 text-indigo-500" /> Everything in Free</li>
            <li className="flex gap-2"><Check size={17} className="mt-0.5 shrink-0 text-indigo-500" /> Minimal &amp; Bold premium PDF templates</li>
            <li className="flex gap-2"><Check size={17} className="mt-0.5 shrink-0 text-indigo-500" /> White-label PDFs — no &quot;Generated by&quot; footer</li>
            <li className="flex gap-2"><Check size={17} className="mt-0.5 shrink-0 text-indigo-500" /> Unlimited invoice history &amp; dashboard</li>
            <li className="flex gap-2"><Check size={17} className="mt-0.5 shrink-0 text-indigo-500" /> 12 premium colour themes</li>
            <li className="flex gap-2"><Check size={17} className="mt-0.5 shrink-0 text-indigo-500" /> Always ad-free</li>
            <li className="flex gap-2"><Check size={17} className="mt-0.5 shrink-0 text-indigo-500" /> 30-day money-back guarantee</li>
          </ul>
          <Link
            href="/?pro=upgrade"
            className="mt-7 inline-flex w-full items-center justify-center rounded-2xl bg-indigo-600 px-6 py-3 font-bold text-white shadow-lg shadow-indigo-500/25 transition-all hover:bg-indigo-700"
          >
            Get Pro — $9/year
          </Link>
        </div>
      </div>

      {/* PDF template styles — show, don't tell */}
      <div className="mb-12">
        <h2 className="text-center text-[20px] font-extrabold tracking-tight text-slate-900">Three PDF styles — pick your look</h2>
        <p className="mx-auto mb-6 mt-1 max-w-xl text-center text-[14px] text-slate-500">
          Classic is free forever. Pro unlocks the Minimal and Bold styles for invoices that match your brand.
        </p>
        <TemplateStyleCards />
      </div>

      {/* Comparison table */}
      <div className="mb-12 overflow-hidden rounded-3xl border border-slate-100 bg-white shadow-sm">
        <table className="w-full text-left">
          <thead>
            <tr className="border-b border-slate-100 bg-slate-50/60 text-[12px] uppercase tracking-wider text-slate-400">
              <th className="px-5 py-3.5 font-bold">Feature</th>
              <th className="px-4 py-3.5 text-center font-bold">Free</th>
              <th className="px-4 py-3.5 text-center font-bold text-indigo-600">Pro</th>
            </tr>
          </thead>
          <tbody>
            {ROWS.map((r) => (
              <tr key={r.feature} className="border-b border-slate-50 last:border-0">
                <td className="px-5 py-3.5 text-[14px] font-medium text-slate-700">{r.feature}</td>
                <td className="px-4 py-3.5 text-center">{<Cell v={r.free} />}</td>
                <td className="px-4 py-3.5 text-center">{<Cell v={r.pro} />}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Guarantee note */}
      <div className="mb-12 rounded-3xl border border-emerald-100 bg-emerald-50/60 p-6 text-center">
        <p className="text-[15px] font-bold text-emerald-900">30-day money-back guarantee</p>
        <p className="mx-auto mt-1 max-w-lg text-[13.5px] leading-relaxed text-emerald-700">
          Try Pro risk-free. If it&apos;s not for you, email{" "}
          <a className="font-semibold underline" href="mailto:support@pdfbillbuilder.com">support@pdfbillbuilder.com</a>{" "}
          within 30 days and we&apos;ll refund you in full.
        </p>
      </div>

      {/* FAQ */}
      <section>
        <h2 className="mb-4 text-[22px] font-extrabold tracking-tight text-slate-900">Pricing questions</h2>
        <div className="space-y-3">
          {PRICING_FAQ.map((f) => (
            <div key={f.q} className="rounded-2xl border border-slate-100 bg-white p-5 shadow-sm">
              <h3 className="mb-1.5 text-[15px] font-bold text-slate-900">{f.q}</h3>
              <p className="text-[14px] leading-relaxed text-slate-500">{f.a}</p>
            </div>
          ))}
        </div>
      </section>

      <JsonLd data={faqSchemaFrom(PRICING_FAQ)} />
      <JsonLd data={breadcrumbSchema([
        { name: "Home", url: SITE.url },
        { name: "Pricing", url: `${SITE.url}/pricing` },
      ])} />
    </PageShell>
  );
}
